/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project1;

import com.mongodb.BasicDBObject;
import com.mongodb.DB;
import com.mongodb.DBCollection;
import com.mongodb.Mongo;
import java.awt.Color;
import java.net.UnknownHostException;
import javax.swing.JOptionPane;
import org.bson.types.ObjectId;
import static project1.User_Update.new_fname;
import static project1.User_Update.old_name;

/**
 *
 * @author DELL
 */
public class Update_owner_book extends javax.swing.JFrame {

    /**
     * Creates new form Update_owner_book
     */
    public Update_owner_book() {
        initComponents();
        pan.setBackground(new Color(0,0,0,0));
        pan2.setBackground(new Color(0,0,0,150));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pan = new javax.swing.JPanel();
        pan2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        course1 = new javax.swing.JLabel();
        sub1 = new javax.swing.JLabel();
        auth1 = new javax.swing.JLabel();
        edi1 = new javax.swing.JLabel();
        qty1 = new javax.swing.JLabel();
        yop1 = new javax.swing.JLabel();
        ppb1 = new javax.swing.JLabel();
        book_id = new javax.swing.JTextField();
        owner_course = new javax.swing.JTextField();
        owner_sub = new javax.swing.JTextField();
        owner_auth = new javax.swing.JTextField();
        owner_edition = new javax.swing.JTextField();
        owner_qty = new javax.swing.JTextField();
        owner_yop = new javax.swing.JTextField();
        owner_ppb = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pan.setBackground(new java.awt.Color(0, 51, 51));

        pan2.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 204));
        jLabel1.setText("Book ID :");

        course1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        course1.setForeground(new java.awt.Color(255, 204, 204));
        course1.setText("Course Name :");

        sub1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        sub1.setForeground(new java.awt.Color(255, 204, 204));
        sub1.setText("Subject :");

        auth1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        auth1.setForeground(new java.awt.Color(255, 204, 204));
        auth1.setText("Author :");

        edi1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        edi1.setForeground(new java.awt.Color(255, 204, 204));
        edi1.setText("Edition :");

        qty1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        qty1.setForeground(new java.awt.Color(255, 204, 204));
        qty1.setText("Quantity in stock :");

        yop1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        yop1.setForeground(new java.awt.Color(255, 204, 204));
        yop1.setText("Year of publication :");

        ppb1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        ppb1.setForeground(new java.awt.Color(255, 204, 204));
        ppb1.setText("Price per book :");

        book_id.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        book_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book_idActionPerformed(evt);
            }
        });

        owner_course.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        owner_course.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                owner_courseActionPerformed(evt);
            }
        });

        owner_sub.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        owner_auth.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        owner_edition.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        owner_edition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                owner_editionActionPerformed(evt);
            }
        });

        owner_qty.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        owner_yop.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        owner_yop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                owner_yopActionPerformed(evt);
            }
        });

        owner_ppb.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 255, 0));
        jButton1.setText("Update Record");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pan2Layout = new javax.swing.GroupLayout(pan2);
        pan2.setLayout(pan2Layout);
        pan2Layout.setHorizontalGroup(
            pan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan2Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(pan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pan2Layout.createSequentialGroup()
                        .addComponent(auth1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(221, 221, 221))
                    .addGroup(pan2Layout.createSequentialGroup()
                        .addGroup(pan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(edi1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pan2Layout.createSequentialGroup()
                                .addGroup(pan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(course1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sub1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(qty1)
                                    .addComponent(yop1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ppb1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(pan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(owner_qty)
                                    .addGroup(pan2Layout.createSequentialGroup()
                                        .addGroup(pan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(owner_ppb, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(pan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(owner_course, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(book_id, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                                                .addGroup(pan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(owner_auth, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(owner_sub, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(owner_edition, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(owner_yop)))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addContainerGap(41, Short.MAX_VALUE))))
            .addGroup(pan2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addGap(131, 131, 131)
                .addComponent(jButton1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pan2Layout.setVerticalGroup(
            pan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(book_id, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(course1)
                    .addComponent(owner_course, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sub1)
                    .addComponent(owner_sub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(auth1)
                    .addComponent(owner_auth, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edi1)
                    .addComponent(owner_edition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qty1)
                    .addComponent(owner_qty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yop1)
                    .addComponent(owner_yop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ppb1)
                    .addComponent(owner_ppb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pan2Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jButton2))
                    .addGroup(pan2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout panLayout = new javax.swing.GroupLayout(pan);
        pan.setLayout(panLayout);
        panLayout.setHorizontalGroup(
            panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(pan2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        panLayout.setVerticalGroup(
            panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(pan2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        getContentPane().add(pan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 29, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/2.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void owner_yopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_owner_yopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_owner_yopActionPerformed

    private void owner_editionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_owner_editionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_owner_editionActionPerformed

    private void owner_courseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_owner_courseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_owner_courseActionPerformed

    private void book_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_book_idActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            Mongo mongo = new Mongo("localhost",27017);
            DB db = mongo.getDB("Book_Store_Management");
            DBCollection collection = db.getCollection("Book_Details_owner");
            
            BasicDBObject document = new BasicDBObject();
            document.append("$set",new BasicDBObject().append("Course",owner_course.getText()).append("subject", owner_sub.getText()).append("author", owner_auth.getText()).append("edition", owner_edition.getText()).append("yop", Integer.parseInt(owner_yop.getText())).append("quantity", Integer.parseInt(owner_qty.getText())).append("price_per_book", Integer.parseInt(owner_ppb.getText())));
            String s = book_id.getText();
            
            BasicDBObject search_document = new BasicDBObject().append("_id",new ObjectId(s));
            
            collection.update(search_document,document);
             
        } 
        catch(UnknownHostException e){
            e.printStackTrace();
        }
        
        JOptionPane.showMessageDialog(null,"Updtaed Succesfully!!");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.toBack();
        setVisible(false);
        new admin_front().toFront();
        new admin_front().setState(java.awt.Frame.NORMAL);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Update_owner_book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Update_owner_book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Update_owner_book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Update_owner_book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Update_owner_book().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel auth1;
    public static javax.swing.JTextField book_id;
    private javax.swing.JLabel course1;
    private javax.swing.JLabel edi1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public static javax.swing.JTextField owner_auth;
    public static javax.swing.JTextField owner_course;
    public static javax.swing.JTextField owner_edition;
    public static javax.swing.JTextField owner_ppb;
    public static javax.swing.JTextField owner_qty;
    public static javax.swing.JTextField owner_sub;
    public static javax.swing.JTextField owner_yop;
    private javax.swing.JPanel pan;
    private javax.swing.JPanel pan2;
    private javax.swing.JLabel ppb1;
    private javax.swing.JLabel qty1;
    private javax.swing.JLabel sub1;
    private javax.swing.JLabel yop1;
    // End of variables declaration//GEN-END:variables
}
